echo .bashrc is being improved

# routine cleanup

    rm -rf ~/delete.me
    rm -rf ~/deleteme
    rm -rf ~/nul



# misc aliases

    alias ll="ls -1AF"
    alias vi=emacs


# misc functions

    function descend {
        local foobar=$PWD
        while true; do
            [ -e $PWD/$1 ] && echo $PWD && break
            [ "$PWD" == '/' ] && break
            cd ..
        done
        cd $foobar
    }    

    function url {
        pushd ~/_bch/_utube
        ./utube $*
        popd
    }





# trap exit if not in subshell, because having your term disappear is annoying.

    [ "$MUSE_PPID" == "" ] && export MUSE_PPID=$PPID
    function exit() { [ "$MUSE_PPID" == "$PPID" ] && echo Try \'builtin exit\' || builtin exit; }


# configure prompt to show git info and to indicate depth of subshell

    source $HOME/.improvement/vendor/git-prompt/git-prompt.sh
    PROMPT_COMMAND='__git_ps1 "[$MUSE_DEPTH] [\w]" "\\\$ "'
    PS1=$PROMPT_COMMAND
    export MUSE_DEPTH=$(( MUSE_DEPTH + 1 ))


# activate vendor tools

    source $HOME/.improvement/vendor/virtualenvwrapper/virtualenvwrapper.sh



#######for i in `ls -a ~`; do
   # if [ -d ~/$i/.tmt ]; then
   #     echo $i
   #     alias $i="~/$i/.tmt/main"
   #     echo $MUSE
#
 #   fi
#done




#export BCH_GIT=~/bch.git

#[ -f ./.pyvenv/bin/activate ] && echo yes || echo no
#[ -f ./.pyvenv/bin/activate ] && source ./.pyvenv/bin/activate
#launchctl load -w /System/Library/LaunchDaemons/com.apple.atrun.plist
echo .bashrc has been improved