#!/bin/zsh
export BH0NEST=0
_up      () {  export BH0NEST=$((${BH0NEST}+1)); }
_down    () {  export BH0NEST=$((${BH0NEST}-1)); }
_tab     () { [[ "${BH0NEST}" == "0" ]] || for i in $( seq ${BH0NEST} ); do printf '|\\t'; done ; }
_color   () { tput setaf $1; [[ "$2" == "." ]] || tput setab $2; shift; shift; echo -n $*; tput sgr0; }
_black   () { _color 15  0 $(_tab)$*; echo; }
_blue    () { _color 15  4 $(_tab)$*; echo; }
_yellow  () { _color 16 11 $(_tab)$*; echo; }
_green   () { _color  0 10 $(_tab)$*; echo; }
_red     () { _color 15  9 $(_tab)$*; echo; }

bh0note ()      { _green "# $*" }
bh0exec ()      { _red exec: $*; $*; }
bh0export ()    { _blue "setting \$$1 := [$2]" ; export $1=$2 }
bh0call ()      { _yellow "++[$*]" ; _up ; $* ; _down ;} # _yellow "--[$*]"; }
bh0source ()    { [[ -f "${1}" ]] && { bh0call source $*; } || { bh0note No activation file $1; }; } 
bh0include ()   { bh0source $(bh0github bryanhann/$1)/activate.sh; }


bh0module () {
    src=${__BH0_URL_BH__}/$1
    dst=${__BH0_DST_BH__}/$1
    [[ -d ${dst} ]] || git clone $src $dst
    echo $dst
}

bh0github () {
    src=https://github.com/$1
    dst=${2-${__BH0_HTTP__}/github.com/$1}
    [[ -d ${dst} ]] || git clone $src $dst
    echo $dst
}

bh0installvim () {
    dst=${HOME}/.config/vim
    url=${__BH0_URL_BH__}/.config.vim
    [[ -d $dst ]] || { git clone ${url} ${dst} ; cd ${dst} ; bh0source ./install ; }
    export VIMINIT='let $MYVIMRC="$HOME/.config/vim/vimrc" | source $MYVIMRC'
}

#   function:   [bh0firstrun]
#   flag:       [$__BHPID__]
#
#   This function returns exit code [0] during the entire first execution of [.zshrc]
#   after which it returns the exit code [1].  Whether this is a first run is deterined
#   by testing the flag [$__BHPID__] which will be set only at the final act of [.zshrc]
#
#   (The flag will be set to the current process ID.)

bh0firstrun () {
    [[ -z "${__BHPID__}" ]] && return 0 || return 1;
}
bh0endfirstrun () {
    bh0export   __BHPID__ $$
    bh0export   PATH ${PATH}:${HOME}/.local/bin
}
