source $HOME/.improvement
.mu_trace ++bashrc
source $MUSE/tools/exittrap/activate
source $MUSE/tools/mu_prompt/activate
source $MUSE/tools/virtualenvwrapper/activate
alias .z=$MUSE/scripts/zlog.bash
.mu_trace --bashrc
